#!/usr/bin/env bash

# Install Cask applications
echo 'Running brew doctor...'
if brew doctor; then
  echo 'Installing brew-cask...'
  brew tap caskroom/cask
  brew install brew-cask
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  echo 'Hide /opt'
  chflags hidden /opt
  echo 'Installing apps...'
  brew cask install google-chrome 
  brew cask install google-drive 
  brew cask install google-notifier 
  brew cask install android-file-transfer 
  brew cask install cyberduck 
  brew cask install java 
  brew cask install phpstorm 
  brew cask install sequel-pro 
  brew cask install textmate 
  brew cask install virtualbox 
  brew cask install atom 
  brew cask install github 
  brew cask install launchrocket 
  brew cask install robomongo 
  brew cask install spotify 
  brew cask install vagrant 
  brew cask install iterm2 
  brew cask install telegram 
  brew cask install the-unarchiver 
  brew cask install clipmenu 
  brew cask install cakebrew 
  brew cask install vlc 
  # paparazzi vagrant slack the-unarchiver daisydisk fluid gpgtools imagealpha
  # transmission fluid kindle send-to-kindle marked sketch skype subtitles
  # teamviewer torbrowserbundle skype
  brew linkapps
  brew cask cleanup
else
  echo 'Can not install brew-cask. Please fix brew first.'
fi
